apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodbytz-api
  labels:
    app: goodbytz
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goodbytz
      component: api
  template:
    metadata:
      labels:
        app: goodbytz
        component: api
    spec:
      containers:
      - name: api
        image: goodbytz-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_SERVER
          value: goodbytz-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: goodbytz-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: goodbytz-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: goodbytz
        - name: MQTT_BROKER_HOST
          value: goodbytz-mqtt
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 